version: "2.2"

services:
  aws:
    image: localstack/localstack:0.12.17
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - HOSTNAME_EXTERNAL=localstack
      - HOSTNAME=localstack
      - SERVICES=sns,sqs,s3,sts,kms
      - DEFAULT_REGION=ap-northeast-2
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=ap-northeast-2
      - KMS_PROVIDER=local-kms
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./.localstack/init.sh:/docker-entrypoint-initaws.d/init-localstack.sh"
      - "./.localstack/kms/seed.yaml:/init/seed.yaml"

  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=test
    ports:
      - "13306:3306"
    volumes:
      - ./.mysql:/docker-entrypoint-initdb.d
    command:
      [mysqld, --character-set-server=utf8, --collation-server=utf8_general_ci]

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "4000:80"
    volumes:
      - ./.nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - user-web

  user-web:
    image: jwilder/dockerize
    depends_on:
      - aws
      - db
