apiVersion: argoproj.io/v1alpha1
kind: WorkflowEventBinding
metadata:
  name: github-event-consumer
spec:
  event:
    # metadata header name must be lowercase to match in selector
    selector: payload.message != ""
  submit:
    workflowTemplateRef:
      name: my-wf-tmple
    arguments:
      parameters:
      - name: message
        valueFrom:
          event: payload.message
