apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: worker-rolebinding
  namespace: argo-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: worker-role
subjects:
- kind: ServiceAccount
  name: worker
  namespace: argo-system
